# Generated by Django 5.2.4 on 2025-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstepmaster',
            name='step_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '承認'), (2, '確認')], default=1),
        ),
        migrations.AlterField(
            model_name='approvalstepmaster',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '社長'), (2, '事業部長'), (3, '課長'), (4, '一般')], null=True),
        ),
    ]
