# Generated by Django 5.2.3 on 2025-07-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(choices=[(1, '事業部'), (2, '課')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='departments.department')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
