# Generated by Django 5.2.4 on 2025-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.IntegerField(choices=[(1, '社長'), (2, '事業部'), (3, '課')], default=3),
        ),
    ]
