# Generated by Django 5.2.4 on 2025-07-19 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allowances', '0001_initial'),
        ('approvals', '0002_approvalstepmaster_step_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTripRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.PositiveSmallIntegerField(choices=[(1, '事前申請'), (2, '精算申請')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '承認待ち'), (2, '却下'), (3, '精算待ち'), (4, '精算済')])),
                ('destination', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('approval_route_master', models.ForeignKey(db_column='approval_route_master_id', on_delete=django.db.models.deletion.PROTECT, related_name='business_trip_requests', to='approvals.approvalroutemaster', verbose_name='承認ルート')),
                ('parent_request', models.ForeignKey(blank=True, db_column='parent_request_id', help_text='事前申請と紐づけるため', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='business_trips.businesstriprequest')),
                ('request_user', models.ForeignKey(db_column='request_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='business_trip_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'db_table': 'business_trip_requests',
            },
        ),
        migrations.CreateModel(
            name='BusinessTripExpenseHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_type', models.PositiveSmallIntegerField(choices=[(1, '交通費'), (2, 'ホテル代')])),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('business_trip_request', models.ForeignKey(db_column='business_trip_request_id', on_delete=django.db.models.deletion.CASCADE, to='business_trips.businesstriprequest')),
            ],
            options={
                'db_table': 'business_trip_expense_histories',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.PROTECT, related_name='approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('business_trip_request', models.ForeignKey(db_column='business_trip_request_id', on_delete=django.db.models.deletion.CASCADE, to='business_trips.businesstriprequest')),
            ],
            options={
                'db_table': 'approval_histories',
            },
        ),
        migrations.CreateModel(
            name='AllowanceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('auto_calculated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('allowance_master', models.ForeignKey(db_column='allowance_master_id', on_delete=django.db.models.deletion.PROTECT, related_name='allowance_histories', to='allowances.allowancemaster', verbose_name='手当マスタ')),
                ('business_trip_request', models.ForeignKey(db_column='business_trip_request_id', on_delete=django.db.models.deletion.CASCADE, to='business_trips.businesstriprequest')),
            ],
            options={
                'db_table': 'allowance_histories',
            },
        ),
    ]
