# Generated by Django 5.2.4 on 2025-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '承認'), (2, '却下'), (3, '確認')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesstripexpensehistory',
            name='arrival_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesstripexpensehistory',
            name='departure_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesstripexpensehistory',
            name='transport_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '電車'), (2, 'バス'), (3, '飛行機'), (4, '社用車'), (5, 'フェリー'), (6, 'タクシー'), (7, 'レンタカー'), (99, 'その他')], null=True),
        ),
        migrations.AddField(
            model_name='businesstriprequest',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
