# Generated by Django 5.2.4 on 2025-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_trips', '0002_approvalhistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancehistory',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
