# Generated by Django 5.2.4 on 2025-07-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_trips', '0003_allowancehistory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='approver',
            field=models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '承認待ち'), (1, '承認'), (2, '却下'), (3, '確認')], default=0),
        ),
    ]
