# Generated by Django 5.2.4 on 2025-07-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_trips', '0004_alter_approvalhistory_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalhistory',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='approvalhistory',
            name='approver',
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='action_user',
            field=models.ForeignKey(db_column='action_user_id', default=1, help_text='申請や承認を行ったユーザー', on_delete=django.db.models.deletion.PROTECT, related_name='acted_approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='アクションユーザー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='next_user',
            field=models.ForeignKey(blank=True, db_column='next_user_id', help_text='次に承認や確認を行うことが期待されているユーザー', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='次アクションユーザー'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '承認待ち'), (1, '承認済'), (2, '却下'), (3, '確認'), (4, '精算済')], default=0),
        ),
    ]
