# Generated by Django 5.2.4 on 2025-08-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_trips', '0005_alter_approvalhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '申請'), (1, '承認待ち'), (2, '却下'), (3, '承認済'), (4, '確認済'), (5, '精算済')], default=0),
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '承認待ち'), (2, '却下'), (3, '承認済'), (4, '精算済')]),
        ),
    ]
