# Generated by Django 5.2.4 on 2025-08-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalstepmaster_step_type_and_more'),
        ('business_trips', '0006_alter_approvalhistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='approval_step_master',
            field=models.ForeignKey(blank=True, db_column='approval_step_master_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.approvalstepmaster'),
        ),
    ]
